# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(height_field=2000, upload_to='img/', width_field=4000)),
                ('username', models.CharField(max_length=20)),
                ('content', models.TextField(blank=True, max_length=200000, null=True)),
            ],
        ),
    ]
