# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
